// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteFileNoContentCode is the HTTP code returned for type DeleteFileNoContent
const DeleteFileNoContentCode int = 204

/*
DeleteFileNoContent File deleted successfully

swagger:response deleteFileNoContent
*/
type DeleteFileNoContent struct {
}

// NewDeleteFileNoContent creates DeleteFileNoContent with default headers values
func NewDeleteFileNoContent() *DeleteFileNoContent {

	return &DeleteFileNoContent{}
}

// WriteResponse to the client
func (o *DeleteFileNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
