// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListFilesOKCode is the HTTP code returned for type ListFilesOK
const ListFilesOKCode int = 200

/*
ListFilesOK List of files retrieved successfully

swagger:response listFilesOK
*/
type ListFilesOK struct {

	/*
	  In: Body
	*/
	Payload []*ListFilesOKBodyItems0 `json:"body,omitempty"`
}

// NewListFilesOK creates ListFilesOK with default headers values
func NewListFilesOK() *ListFilesOK {

	return &ListFilesOK{}
}

// WithPayload adds the payload to the list files o k response
func (o *ListFilesOK) WithPayload(payload []*ListFilesOKBodyItems0) *ListFilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list files o k response
func (o *ListFilesOK) SetPayload(payload []*ListFilesOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*ListFilesOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
