// Code generated by go-swagger; DO NOT EDIT.

// Package restapi File Storage API
//
//	API for file storage and retrieval
//	Schemes:
//	  https
//	Host: localhost
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - multipart/form-data
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
