// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for file storage and retrieval",
    "title": "File Storage API",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/files": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a list of all files",
        "operationId": "listFiles",
        "responses": {
          "200": {
            "description": "List of files retrieved successfully",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "description": "The ID of the file",
                    "type": "string"
                  },
                  "url": {
                    "description": "The URL of the file",
                    "type": "string",
                    "format": "uri"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Upload a file",
        "operationId": "uploadFile",
        "parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "File uploaded successfully",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "description": "The ID of the uploaded file",
                  "type": "string"
                },
                "url": {
                  "description": "The URL of the uploaded file",
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          }
        }
      }
    },
    "/files/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Download a file by ID",
        "operationId": "downloadFile",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "File downloaded successfully",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "description": "The ID of the downloaded file",
                  "type": "string"
                },
                "url": {
                  "description": "The URL of the downloaded file",
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "summary": "Delete a file by ID",
        "operationId": "deleteFile",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "File deleted successfully"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for file storage and retrieval",
    "title": "File Storage API",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/files": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a list of all files",
        "operationId": "listFiles",
        "responses": {
          "200": {
            "description": "List of files retrieved successfully",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ListFilesOKBodyItems0"
              }
            }
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Upload a file",
        "operationId": "uploadFile",
        "parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "File uploaded successfully",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "description": "The ID of the uploaded file",
                  "type": "string"
                },
                "url": {
                  "description": "The URL of the uploaded file",
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          }
        }
      }
    },
    "/files/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Download a file by ID",
        "operationId": "downloadFile",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "File downloaded successfully",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "description": "The ID of the downloaded file",
                  "type": "string"
                },
                "url": {
                  "description": "The URL of the downloaded file",
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "summary": "Delete a file by ID",
        "operationId": "deleteFile",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "File deleted successfully"
          }
        }
      }
    }
  },
  "definitions": {
    "ListFilesOKBodyItems0": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The ID of the file",
          "type": "string"
        },
        "url": {
          "description": "The URL of the file",
          "type": "string",
          "format": "uri"
        }
      }
    }
  }
}`))
}
